/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2022 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_CSDKERR_H
# define HEADER_CSDKERR_H

# include <openssl/symhacks.h>

# define CSDKerr(f, r) ERR_CSDK_error((f), (r), OPENSSL_FILE, OPENSSL_LINE)


# ifdef  __cplusplus
extern "C" {
# endif
int ERR_load_CSDK_strings(void);
void ERR_unload_CSDK_strings(void);
void ERR_CSDK_error(int function, int reason, const char *file, int line);
# ifdef  __cplusplus
}
# endif

/*
 * CSDK function codes.
 */
# define CSDK_F_CSDK_BIND_HELPER                          100

/*
 * CSDK reason codes.
 */
# define CSDK_R_ENGINE_BIND_INIT_FAILED                   100
# define CSDK_R_ENGINE_BIND_NAME_FAILED                   101
# define CSDK_R_ENGINE_BIND_SET_CIPHERS_FAILED            102
# define CSDK_R_ENGINE_BIND_SET_DESTROY_FAILED            103
# define CSDK_R_ENGINE_BIND_SET_FAILED                    104
# define CSDK_R_ENGINE_BIND_SET_FINISH_FAILED             105

#endif
