/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2022 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include "csdk_err.h"

#ifndef OPENSSL_NO_ERR

static ERR_STRING_DATA CSDK_str_functs[] = {
    {ERR_PACK(0, CSDK_F_CSDK_BIND_HELPER, 0), "csdk_bind_helper"},
    {0, NULL}
};

static ERR_STRING_DATA CSDK_str_reasons[] = {
    {ERR_PACK(0, 0, CSDK_R_ENGINE_BIND_INIT_FAILED), "engine bind init failed"},
    {ERR_PACK(0, 0, CSDK_R_ENGINE_BIND_NAME_FAILED), "engine bind name failed"},
    {ERR_PACK(0, 0, CSDK_R_ENGINE_BIND_SET_CIPHERS_FAILED),
    "engine bind set ciphers failed"},
    {ERR_PACK(0, 0, CSDK_R_ENGINE_BIND_SET_DESTROY_FAILED),
    "engine bind set destroy failed"},
    {ERR_PACK(0, 0, CSDK_R_ENGINE_BIND_SET_FAILED), "engine bind set failed"},
    {ERR_PACK(0, 0, CSDK_R_ENGINE_BIND_SET_FINISH_FAILED),
    "engine bind set finish failed"},
    {0, NULL}
};

#endif

static int lib_code = 0;
static int error_loaded = 0;

int ERR_load_CSDK_strings(void)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();

    if (!error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(lib_code, CSDK_str_functs);
        ERR_load_strings(lib_code, CSDK_str_reasons);
#endif
        error_loaded = 1;
    }
    return 1;
}

void ERR_unload_CSDK_strings(void)
{
    if (error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(lib_code, CSDK_str_functs);
        ERR_unload_strings(lib_code, CSDK_str_reasons);
#endif
        error_loaded = 0;
    }
}

void ERR_CSDK_error(int function, int reason, const char *file, int line)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();
    ERR_PUT_error(lib_code, function, reason, file, line);
}
